@startuml /home/thorsten/code/landscape/ruv/landscapeapp
left to right direction
header R+V Anwendungslandschaft

allow_mixing

node fromon2csv {
	node lib {
		database JSON2CSVParser
	}
}		

node project {
		database lookupon
		database previewon
		database settings.yml
}

node landscapeapp {
	class webpack.config.prod
	class webpack.config.dev
	
	package tools {
		class fundingHistoryData
		class yaml
		class checkLinks
		class retry
		class sitemap
		class testGithub
		class renderLandscape
		class validateLandscapeKeys
		class reportToSlackTest
		class fundingForMasterBranch
		class chalkConfig
		class srcServer
		class addRobots
		class testCi
		class reportToSlack
		class analyzeBundle
		class fetchGithubStartDate
		class fetchImages
		class startMessage
		class fetchGithubStats
		class testCropFrame
		class autocropImages
		class removeQuotes
		class actualTwitter
		class hostImages
		class setupServer
		class twitterClient
		class twitter
		class distServer
		class progressReporter
		class calculateNumberOfTweets
		class githubDates
		class removeUnusedHostedLogos
		class getRepositoryInfo
		class rpRetry
		class crunchbase
		class reporter
		class addExternalInfo
		class debugCheckLinks
		class fileMock
		class fetchBestPractices
		class ciServer
		class assetsTransformer
		class rpRetryTest
		class ensureHttps
		class checkLandscape
		class settings
		class generateJson
		class fatalErrors
		class build
		class fundingHistoryPage
	}
	
	package src {
		class iframeResizer
		class index
		class webpack-public-path
	
		package types {
			class index
			class fields
		}
	
		package components {
			class Grouping
			class ComboboxMultiSelector
			class ExportCsv
			class Note
			class PresetsContainer
			class ExportCsvContainer
			class GroupingTypeContainer
			class TweetButton
			class HomePageScrollerContainer
			class LandscapeSelector
			class InternalLink
			class HomePageContainer
			class SortFieldSelector
			class Sorting
			class DelayRender
			class EmbeddedFooter
			class RadioSelector
			class Ad
			class ComboboxSelector
			class Footer
			class HeadquartersFilterContainer
			class ResetFiltersContainer
			class OrganizationFilterContainer
			class Root
			class ItemDialogContent
			class HomePage
			class NotFoundPage
			class SortFieldContainer
			class TreeSelector
			class Filters
			class HeaderContainer
			class ItemDialogButtonsContainer
			class CheckboxSelector
			class MainContent
			class LicenseFilterContainer
			class Presets
			class HomePageUrlContainer
			class LandscapeFilterContainer
			class CustomAutoSizer
			class App
			class Summary
			class Header
			class ProjectFilterContainer
			class ItemDialog
			class MainContentContainer
			class GroupingSelector
			class ItemDialogContainer
			class ItemDialogButtons
			class OssFilterContainer
			class SummaryContainer

			package BigPicture {
				class FullscreenLandscape
				class ZoomButtonsContainer
				class ExtraLandscapeContentContainer
				class LandscapeInfo
				class FullscreenButton
				class OtherLandscapeLink
				class Zoom
				class SwitchButton
				class ZoomContainer
				class MainFullscreenLandscapeContainer
				class SwitchButtonContainer
				class ZoomButtons
				class FullscreenButtonContainer
				class index
				class ExtraFullscreenLandscapeContainer
				class Elements
				class LandscapeContent
				class MainLandscapeContentContainer
			}			
		}
		
		package reducers {
			class api
			class bus
			class mainReducer
			class index
		}

		package utils {
			class unpackArray
			class saneName
			class isDesktop
			class groupingLabel
			class groupingOrder
			class formatNumber
			class createSelector
			class summaryCalculator
			class itemsCalculator
			class isMobile
			class selectedItemCalculator
			class packArray
			class isEmbed
			class zoom
			class shortRepoName
			class isIphone
			class stringOrSpecial
			class formatAmount
			class csvExporter
			class formatCity
			class isGoogle
			class syncToUrl
		}
	
		package store {
			class configureStore
		}
	}
	
	
	checkLinks ..> retry
	checkLinks ..> settings
	sitemap ..> settings
	testGithub ..> githubDates
	renderLandscape ..> settings
	validateLandscapeKeys ..> settings
	srcServer ..> webpack.config.dev
	srcServer ..> settings
	analyzeBundle ..> webpack.config.prod
	fetchGithubStartDate ..> fatalErrors
	fetchGithubStartDate ..> settings
	fetchGithubStartDate ..> reporter
	fetchGithubStartDate ..> getRepositoryInfo
	fetchGithubStartDate ..> progressReporter
	fetchGithubStartDate ..> githubDates
	fetchImages ..> fatalErrors
	fetchImages ..> rpRetry
	fetchImages ..> saneName
	fetchImages ..> settings
	fetchImages ..> progressReporter
	fetchImages ..> reporter
	startMessage ..> chalkConfig
	fetchGithubStats ..> fatalErrors
	fetchGithubStats ..> rpRetry
	fetchGithubStats ..> reporter
	fetchGithubStats ..> settings
	fetchGithubStats ..> progressReporter
	fetchGithubStats ..> shortRepoName
	fetchGithubStats ..> getRepositoryInfo
	fetchGithubStats ..> githubDates
	testCropFrame ..> processSvg
	autocropImages ..> settings
	removeQuotes ..> settings
	removeQuotes ..> yaml
	hostImages ..> settings
	hostImages ..> fetchImages
	hostImages ..> yaml
	setupServer ..> settings
	twitter ..> fatalErrors
	twitter ..> settings
	twitter ..> reporter
	twitter ..> actualTwitter
	twitter ..> twitterClient
	twitter ..> retry
	twitter ..> progressReporter
	distServer ..> chalkConfig
	distServer ..> settings
	calculateNumberOfTweets ..> twitterClient
	calculateNumberOfTweets ..> settings
	calculateNumberOfTweets ..> yaml
	githubDates ..> rpRetry
	removeUnusedHostedLogos ..> settings
	getRepositoryInfo ..> shortRepoName
	getRepositoryInfo ..> rpRetry
	rpRetry ..> retry
	crunchbase ..> fatalErrors
	crunchbase ..> ensureHttps
	crunchbase ..> reporter
	crunchbase ..> settings
	crunchbase ..> progressReporter
	addExternalInfo ..> fatalErrors
	addExternalInfo ..> settings
	addExternalInfo ..> actualTwitter
	addExternalInfo ..> yaml
	addExternalInfo ..> fetchImages
	addExternalInfo ..> crunchbase
	addExternalInfo ..> fetchGithubStats
	addExternalInfo ..> fetchGithubStartDate
	addExternalInfo ..> twitter
	addExternalInfo ..> fetchBestPractices
	addExternalInfo ..> shortRepoName
	debugCheckLinks ..> checkLinks
	fetchBestPractices ..> fatalErrors
	fetchBestPractices ..> retry
	fetchBestPractices ..> reporter
	fetchBestPractices ..> settings
	fetchBestPractices ..> progressReporter
	ciServer ..> chalkConfig
	ciServer ..> settings
	rpRetryTest ..> rpRetry
	checkLandscape ..> settings
	generateJson ..> settings
	generateJson ..> actualTwitter
	generateJson ..> saneName
	generateJson ..> formatCity
	generateJson ..> packArray
	build ..> webpack.config.prod
	build ..> chalkConfig
	webpack.config.prod ..> settings
	fields ..> unpackArray
	Grouping ..> GroupingTypeContainer
	PresetsContainer ..> createSelector
	PresetsContainer ..> Presets
	PresetsContainer ..> syncToUrl
	ExportCsvContainer ..> ExportCsv
	ExportCsvContainer ..> mainReducer
	GroupingTypeContainer ..> GroupingSelector
	GroupingTypeContainer ..> mainReducer
	GroupingTypeContainer ..> fields
	HomePageScrollerContainer ..> itemsCalculator
	LandscapeSelector ..> TreeSelector
	InternalLink ..> isEmbed
	HomePageContainer ..> createSelector
	HomePageContainer ..> HomePage
	HomePageContainer ..> mainReducer
	HomePageContainer ..> isEmbed
	HomePageContainer ..> itemsCalculator
	HomePageContainer ..> selectedItemCalculator
	SortFieldSelector ..> ComboboxSelector
	Sorting ..> SortFieldContainer
	HeadquartersFilterContainer ..> TreeSelector
	HeadquartersFilterContainer ..> mainReducer
	HeadquartersFilterContainer ..> fields
	ResetFiltersContainer ..> ResetFilters
	ResetFiltersContainer ..> mainReducer
	OrganizationFilterContainer ..> ComboboxMultiSelector
	OrganizationFilterContainer ..> mainReducer
	OrganizationFilterContainer ..> fields
	Root ..> App
	ItemDialogContent ..> syncToUrl
	ItemDialogContent ..> formatNumber
	ItemDialogContent ..> isMobile
	ItemDialogContent ..> InternalLink
	ItemDialogContent ..> fields
	ItemDialogContent ..> isGoogle
	ItemDialogContent ..> TweetButton
	HomePage ..> Filters
	HomePage ..> Grouping
	HomePage ..> Sorting
	HomePage ..> PresetsContainer
	HomePage ..> Ad
	HomePage ..> CustomAutoSizer
	HomePage ..> TweetButton
	HomePage ..> MainContentContainer
	HomePage ..> HomePageUrlContainer
	HomePage ..> HomePageScrollerContainer
	HomePage ..> ResetFiltersContainer
	HomePage ..> ItemDialogContainer
	HomePage ..> ItemDialogButtonsContainer
	HomePage ..> HeaderContainer
	HomePage ..> SummaryContainer
	HomePage ..> ExportCsvContainer
	HomePage ..> Footer
	HomePage ..> EmbeddedFooter
	HomePage ..> isIphone
	HomePage ..> isMobile
	HomePage ..> isDesktop
	HomePage ..> isGoogle
	HomePage ..> bus
	HomePage ..> MainLandscapeContentContainer
	HomePage ..> ExtraLandscapeContentContainer
	HomePage ..> SwitchButtonContainer
	HomePage ..> ZoomButtonsContainer
	HomePage ..> FullscreenButtonContainer
	SortFieldContainer ..> SortFieldSelector
	SortFieldContainer ..> mainReducer
	Filters ..> ProjectFilterContainer
	Filters ..> LicenseFilterContainer
	Filters ..> OrganizationFilterContainer
	Filters ..> HeadquartersFilterContainer
	Filters ..> LandscapeFilterContainer
	Filters ..> fields
	HeaderContainer ..> Header
	HeaderContainer ..> mainReducer
	ItemDialogButtonsContainer ..> createSelector
	ItemDialogButtonsContainer ..> ItemDialogButtons
	ItemDialogButtonsContainer ..> mainReducer
	ItemDialogButtonsContainer ..> itemsCalculator
	ItemDialogButtonsContainer ..> selectedItemCalculator
	MainContent ..> InternalLink
	MainContent ..> isEmbed
	MainContent ..> isMobile
	MainContent ..> DelayRender
	MainContent ..> fields
	LicenseFilterContainer ..> TreeSelector
	LicenseFilterContainer ..> mainReducer
	LicenseFilterContainer ..> fields
	HomePageUrlContainer ..> createSelector
	HomePageUrlContainer ..> syncToUrl
	HomePageUrlContainer ..> mainReducer
	HomePageUrlContainer ..> configureStore
	LandscapeFilterContainer ..> LandscapeSelector
	LandscapeFilterContainer ..> mainReducer
	LandscapeFilterContainer ..> fields
	CustomAutoSizer ..> isMobile
	App ..> HomePageContainer
	App ..> NotFoundPage
	Summary ..> formatNumber
	ProjectFilterContainer ..> TreeSelector
	ProjectFilterContainer ..> mainReducer
	ProjectFilterContainer ..> fields
	ItemDialog ..> ItemDialogContent
	ItemDialog ..> ItemDialogButtonsContainer
	ItemDialog ..> isIphone
	ItemDialog ..> fields
	MainContentContainer ..> MainContent
	MainContentContainer ..> mainReducer
	MainContentContainer ..> itemsCalculator
	GroupingSelector ..> ComboboxSelector
	ItemDialogContainer ..> createSelector
	ItemDialogContainer ..> ItemDialog
	ItemDialogContainer ..> mainReducer
	ItemDialogContainer ..> itemsCalculator
	ItemDialogContainer ..> selectedItemCalculator
	FullscreenLandscape ..> LandscapeContent
	FullscreenLandscape ..> HomePageUrlContainer
	ZoomButtonsContainer ..> ZoomButtons
	ZoomButtonsContainer ..> mainReducer
	ZoomButtonsContainer ..> zoom
	ExtraLandscapeContentContainer ..> LandscapeContent
	ExtraLandscapeContentContainer ..> mainReducer
	ExtraLandscapeContentContainer ..> itemsCalculator
	SwitchButton ..> InternalLink
	SwitchButton ..> isEmbed
	SwitchButton ..> TweetButton
	ZoomContainer ..> Zoom
	MainFullscreenLandscapeContainer ..> FullscreenLandscape
	MainFullscreenLandscapeContainer ..> itemsCalculator
	SwitchButtonContainer ..> SwitchButton
	SwitchButtonContainer ..> mainReducer
	SwitchButtonContainer ..> syncToUrl
	FullscreenButtonContainer ..> FullscreenButton
	FullscreenButtonContainer ..> mainReducer
	index ..> MainLandscapeContentContainer
	index ..> ExtraLandscapeContentContainer
	index ..> SwitchButtonContainer
	index ..> ZoomContainer
	index ..> ZoomButtonsContainer
	index ..> MainFullscreenLandscapeContainer
	index ..> ExtraFullscreenLandscapeContainer
	index ..> FullscreenButtonContainer
	ExtraFullscreenLandscapeContainer ..> FullscreenLandscape
	ExtraFullscreenLandscapeContainer ..> itemsCalculator
	Elements ..> InternalLink
	Elements ..> fields
	LandscapeContent ..> Elements
	LandscapeContent ..> LandscapeInfo
	LandscapeContent ..> OtherLandscapeLink
	MainLandscapeContentContainer ..> LandscapeContent
	MainLandscapeContentContainer ..> mainReducer
	MainLandscapeContentContainer ..> itemsCalculator
	OssFilterContainer ..> ComboboxSelector
	OssFilterContainer ..> mainReducer
	OssFilterContainer ..> fields
	SummaryContainer ..> Summary
	SummaryContainer ..> summaryCalculator
	api ..> unpackArray
	mainReducer ..> api
	mainReducer ..> syncToUrl
	mainReducer ..> zoom
	mainReducer ..> bus
	mainReducer ..> itemsCalculator
	mainReducer ..> csvExporter
	index ..> mainReducer
	groupingLabel ..> fields
	groupingOrder ..> fields
	summaryCalculator ..> createSelector
	summaryCalculator ..> itemsCalculator
	itemsCalculator ..> createSelector
	itemsCalculator ..> fields
	itemsCalculator ..> groupingLabel
	itemsCalculator ..> groupingOrder
	itemsCalculator ..> formatAmount
	itemsCalculator ..> syncToUrl
	itemsCalculator ..> stringOrSpecial
	syncToUrl ..> mainReducer
	syncToUrl ..> fields
	syncToUrl ..> SortFieldContainer
	syncToUrl ..> isEmbed
	index ..> configureStore
	index ..> Root
	index ..> mainReducer
	index ..> isIphone
	configureStore ..> reducers
	webpack.config.dev ..> settings

	Ad .. settings.yml
	App .. settings.yml
	ExtraFullscreenLandscapeContainer .. settings.yml
	ExtraLandscapeContentContainer  .. settings.yml
	MainFullscreenLandscapeContainer .. settings.yml
	MainLandscapeContentContainer .. settings.yml
	SwitchButtonContainer .. settings.yml
	Footer .. settings.yml
	Header .. settings.yml
	HomePageContainer .. settings.yml
	HomePage .. settings.yml
	ItemDialogContent .. settings.yml
	PresetsContainer .. settings.yml
	TweetButton .. settings.yml
	index .. settings.yml
	api .. previewon
	mainReducer .. settings.yml
	fields .. lookupon
	fields .. settings.yml
	csvExporter .. JSON2CSVParser
	itemsCalculator .. settings.yml
	syncToUrl .. settings.yml
}
@enduml
